### ISSUE TITLE
install auth starter kit

### ISSUE THREAD

**Issue by sweet202020** [sweet202020/git-shop#1]
installa laravel breeze ed esegui lo scaffolding del progetto iniziale
`composer require laravel/breeze --dev`
`php artisan breeze:install`
installa il pacchetto pacific dev per boostrap
`composer require pacificdev/laravel_9_preset`
`php artisan preset:ui bootstrap --auth`

**Comment by RodrigoFantechi** [comment]
ci lavorerò io!
